'''
Created on Apr 10, 2011

@author: pyridoxus
'''
BLACK = 0, 0, 0
ANIMATIONFRAMES = 100

objectList = [("alligator.bmp",     "baligator3.wav"),
              ("baseball.bmp",      "Ball_Hit_Cheer.wav"),
              ("basketball.bmp",    "dribble.wav"),
              ("bat.bmp",           "bat1.wav"),
              ("billiards.bmp",     "Break_2.wav"),
              ("bowling.bmp",       "bowling1.wav"),
              ("brook.bmp",         "brook.wav"),
              ("broom.bmp",         "broom1.wav"),
              ("chicken.bmp",       "CHICKEN2.WAV"),
              ("chimps.bmp",        "CHIMP1.WAV"),
              ("cougar.bmp",        "cougar.wav"),
              ("cow.bmp",           "COW.WAV"),
              ("coyote.bmp",        "coyote3.wav"),
              ("dog.bmp",           "dog2.wav"),
              ("dolphin.bmp",       "dolphin1.wav"),
              ("elephant.bmp",      "elephant3.wav"),
              ("fire.bmp",          "fire.wav"),
              ("foxsquirrel01.bmp", "SQ1.wav"),
              ("frog.bmp",          "FROG.WAV"),
              ("goat.bmp",          "GOAT.WAV"),
              ("grizzlybear.bmp",   "grizzlybear.wav"),
              ("harley.bmp",        "harley.wav"),
              ("horse.bmp",         "HORSE.WAV"),
              ("hyena.bmp",         "hyena1.wav"),
              ("kitten.bmp",        "kitten3.wav"),
              ("koala.bmp",         "koala.wav"),
              ("lawnmower.bmp",     "lawnmower.wav"),
              ("lemur.bmp",         "lemur.wav"),
              ("lion.bmp",          "lion.wav"),
              ("monkies.bmp",       "monkeys1.wav"),
              ("ocean.bmp",         "SEASHORE.WAV"),
              ("penguin.bmp",       "penguin3.wav"),
              ("pig.bmp",           "big_pig_snort.wav"),
              ("polarbear.bmp",     "bear_polar.wav"),
              ("police.bmp",        "hiwaycop.wav"),
              ("prairie-dog.bmp",   "prairedog.wav"),
              ("raccoon.bmp",       "raccoon2.wav"),
              ("rattlesnake.bmp",   "rattlesnakerattle.wav"),
              ("seal.bmp",          "sealion.wav"),
              ("sea-lion.bmp",      "seal.wav"),
              ("semi-truck.bmp",    "trckstrt.wav"),
              ("snake.bmp",         "snakeatt.wav"),
              ("tennis.bmp",        "tennis.wav"),
              ("train.bmp",         "train.wav"),
              ("vacuum.bmp",        "Vacuum3.wav"),
              ("wolf.bmp",          "wolf5.wav"),
              ("zebra.bmp",         "zebra2.wav"),
            ]